export default {
  // APP
  APP: 'APP',
  TRANSACTION: 'TRANSACTION',
  INSIGHTS: 'INSIGHTS',
  SENDMONEY: 'SENDMONEY',

  // MAIN
  MAIN: 'MAIN',
  AUTH: 'AUTH',

  // MODAL
  LOGIN: 'LOGIN',

  // TABS
  DASHBOARD: 'DASHBOARD',
  ACCOUNTS: 'ACCOUNTS',
  PAYMENTS: 'PAYMENTS',
  CARDS: 'CARDS',
};
